# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AntiSleep' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AntiSleep

end

target 'AntiSleep WatchKit App' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AntiSleep WatchKit App

end

target 'AntiSleep WatchKit Extension' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AntiSleep WatchKit Extension
	pod 'Alamofire'
	pod 'AlamofireImage', '~> 4.1'

end
